/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/tennis-court.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/tennis-court.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Pivot" position={[0, 0, 8.813]} rotation={[-0.401, 0.525, -0.869]}>
          <PerspectiveCamera name="Camera" makeDefault={true} far={100} near={0.1} fov={22.895} position={[3.236, 4.401, 18.895]} rotation={[-0.229, 0.165, 1.189]} />
        </group>
        <group name="Empty" position={[2.017, 0.509, 9.172]} />
        <group name="Tennis_Court001">
          <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['paint.001']} position={[-15.409, 0.07, 16.428]} />
        </group>
        <group name="Tennis_Court002">
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['paint.002']} position={[-15.409, 0.07, 16.428]} />
        </group>
        <group name="Tennis_Court003">
          <group name="Area010" position={[0, 5.915, 1.851]} rotation={[-1.838, 0, -Math.PI]} scale={[0.106, 0.349, 0.451]} />
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['paint.006']} position={[-15.405, 1.237, 15.434]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['paint.006']} position={[-15.409, 0.07, 16.428]} />
          <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['paint.006']} position={[-15.375, 0, 17.529]} />
        </group>
        <group name="Tennis_Court004">
          <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['paint.007']} position={[-15.375, 0, 0.303]} />
          <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['paint.007']} position={[-15.409, 0.07, -0.798]} />
          <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['paint.007']} position={[-15.405, 1.237, -1.791]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group name="Tennis_Court005">
          <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['paint.008']} position={[-15.409, 0.07, -0.798]} />
        </group>
        <group name="Tennis_Court006">
          <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials['paint.009']} position={[-15.409, 0.07, -0.798]} />
        </group>
        <group name="Tennis_Court007">
          <group name="Area011" position={[-30.813, 5.915, -1.548]} rotation={[-1.304, 0, 0]} scale={[0.106, 0.349, 0.451]} />
          <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials['paint.010']} position={[-15.405, 1.237, -1.791]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={materials['paint.010']} position={[-15.409, 0.07, -0.798]} />
          <mesh name="Cube049" geometry={nodes.Cube049.geometry} material={materials['paint.010']} position={[-15.375, 0, 0.303]} />
        </group>
        <group name="Tennis_Court008">
          <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={materials['paint.011']} position={[-15.375, 0, 0.303]} />
          <mesh name="Cube051" geometry={nodes.Cube051.geometry} material={materials['paint.011']} position={[-15.409, 0.07, -0.798]} />
        </group>
        <group name="Tennis_Court009">
          <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials['paint.012']} position={[-15.409, 0.07, -0.798]} />
        </group>
        <group name="Tennis_Court010">
          <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials['paint.013']} position={[-15.409, 0.07, -0.798]} />
        </group>
        <group name="Tennis_Court011">
          <group name="Area012" position={[-30.813, 5.915, -1.548]} rotation={[-1.304, 0, 0]} scale={[0.106, 0.349, 0.451]} />
          <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials['paint.014']} position={[-15.405, 1.237, -1.791]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={materials['paint.014']} position={[-15.409, 0.07, -0.798]} />
          <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials['paint.014']} position={[-15.375, 0, 0.303]} />
        </group>
        <group name="NurbsPath008" position={[3.475, 0, 6.668]} />
        <group name="GPencil" position={[3.475, 0, 6.945]} />
        <group name="Tennis_Court">
          <group name="Area002" position={[-13.605, 5.915, 0]} rotation={[-Math.PI / 2, -0.267, -Math.PI / 2]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area" position={[0, 5.915, 15.777]} rotation={[-1.304, 0, 0]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area001" position={[-14.059, 5.915, 16.193]} rotation={[-1.38, -0.187, -0.767]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area003" position={[14.059, 5.915, 16.193]} rotation={[-1.38, 0.187, 0.767]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area004" position={[13.605, 5.915, 0]} rotation={[-Math.PI / 2, 0.267, Math.PI / 2]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area005" position={[0, 5.915, -15.777]} rotation={[-1.838, 0, -Math.PI]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area006" position={[14.059, 5.915, -16.193]} rotation={[-1.762, 0.187, 2.374]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area007" position={[-13.993, 6.044, -16.504]} rotation={[-1.762, -0.187, -2.374]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area008" position={[-30.813, 5.915, 15.678]} rotation={[-1.304, 0, 0]} scale={[0.106, 0.349, 0.451]} />
          <group name="Area009" position={[0, 5.915, 1.851]} rotation={[-1.838, 0, -Math.PI]} scale={[0.106, 0.349, 0.451]} />
          <mesh name="NurbsPath001" geometry={nodes.NurbsPath001.geometry} material={materials['Material.015']} position={[0, 0.175, 8.813]} />
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Grass} position={[0, 0, 8.813]} />
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['paint.005']} position={[-15.375, 0, 17.529]} />
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['paint.005']} position={[-15.409, 0.07, 16.428]} />
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['paint.005']} position={[-15.405, 1.237, 15.434]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['paint.005']} position={[0.768, 1.665, 17.575]} rotation={[0, -1.571, 0]} />
          <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['paint.005']} position={[14.494, 0.07, 17.548]} rotation={[0, 1.571, 0]} />
          <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['paint.005']} position={[13.618, 1.237, 17.543]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['paint.005']} position={[15.469, 0, -17.575]} rotation={[0, -1.571, 0]} />
          <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['paint.005']} position={[14.494, 0.07, -17.546]} rotation={[0, 1.571, 0]} />
          <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['paint.003']} position={[13.618, 1.237, -17.552]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['paint.003']} position={[-11.873, 0, -17.575]} rotation={[0, -1.571, 0]} />
          <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['paint.005']} position={[14.477, 0.07, 17.548]} rotation={[0, 1.571, 0]} />
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['paint.005']} position={[13.622, 1.237, 17.543]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['paint.003']} position={[16.047, 0.07, -17.547]} rotation={[0, 1.571, 0]} />
          <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['paint.003']} position={[15.192, 1.237, -17.552]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['paint.003']} position={[-13.479, 0, -17.575]} rotation={[0, -1.571, 0]} />
          <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['paint.003']} position={[-14.63, 1.26, -17.547]} rotation={[0, 1.571, 0]} />
          <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials['paint.003']} position={[13.259, 1.237, -17.552]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials['Material.019']} position={[0, -0.004, 17.324]} />
          <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials['Material.019']} position={[-15.153, -0.004, 17.287]} rotation={[0, -Math.PI / 4, 0]} />
          <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials['Material.019']} position={[-15.153, -0.004, 0]} rotation={[0, -1.571, 0]} />
          <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials['Material.019']} position={[15.153, -0.004, 17.287]} rotation={[0, Math.PI / 4, 0]} />
          <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials['Material.019']} position={[15.153, -0.004, 0]} rotation={[0, 1.571, 0]} />
          <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['Material.019']} position={[0, -0.004, -17.324]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials['Material.019']} position={[15.153, -0.004, -17.287]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
          <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['Material.019']} position={[-15.153, -0.004, -17.287]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
          <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['Material.019']} position={[1.587, 0.01, 1.54]} />
          <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['paint.004']} position={[0, -0.002, 16.208]} rotation={[-0.291, 0, 0]} />
          <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['paint.004']} position={[0, 1.689, 16.257]} />
          <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['paint.004']} position={[0, 0.415, 15.729]} />
          <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials['wood.001']} position={[0, 0.415, 15.729]} />
          <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials['paint.003']} position={[-2.086, 0, 17.124]} rotation={[0, Math.PI / 2, 0]} />
          <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials['paint.005']} position={[-2.086, 0, 17.124]} rotation={[0, Math.PI / 2, 0]} />
          <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials['Material.017']} position={[-2.086, 0, 17.124]} rotation={[0, Math.PI / 2, 0]} />
          <mesh name="Cube043" geometry={nodes.Cube043.geometry} material={materials['paint.003']} position={[2.089, 0, 17.124]} rotation={[0, Math.PI / 2, 0]} />
          <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials['paint.005']} position={[2.089, 0, 17.124]} rotation={[0, Math.PI / 2, 0]} />
          <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={materials['Material.017']} position={[2.089, 0, 17.124]} rotation={[0, Math.PI / 2, 0]} />
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['paint.003']} position={[0, -0.003, 15.212]} />
          <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['brass.001']} position={[0, 1.013, 15.212]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['brass.001']} position={[0, 0.753, 15.259]} />
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['brass.001']} position={[0, 0.759, 15.239]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['brass.001']} position={[-0.009, 0.714, 15.295]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['paint.003']} position={[0, 0.827, 15.144]} />
          <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['metal.002']} position={[0, 0.489, 15.143]} />
          <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials['paint.003']} position={[0, -0.003, 2.412]} rotation={[0, 0, -Math.PI]} />
          <mesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={materials['metal.002']} position={[0, 1.021, 15.099]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder009" geometry={nodes.Cylinder009.geometry} material={materials['metal.002']} position={[0, 1.018, 14.974]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials['metal.002']} position={[0, 1.021, 2.526]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['metal.002']} position={[0, 1.018, 2.652]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder012" geometry={nodes.Cylinder012.geometry} material={materials['paint.003']} position={[0, 0.827, 2.481]} rotation={[0, 0, -Math.PI]} />
          <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials['metal.002']} position={[0, 0.489, 2.482]} rotation={[0, 0, -Math.PI]} />
          <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={materials['metal.002']} position={[0, 0.812, 2.343]} rotation={[0.119, 0, 0]} />
          <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials['paint.003']} position={[0, -0.003, -2.413]} />
          <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials['brass.001']} position={[0, 1.013, -2.413]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials['brass.001']} position={[0, 0.753, -2.366]} />
          <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials['brass.001']} position={[0, 0.759, -2.386]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder019" geometry={nodes.Cylinder019.geometry} material={materials['brass.001']} position={[-0.009, 0.714, -2.33]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials['paint.003']} position={[0, 0.827, -2.481]} />
          <mesh name="Cylinder021" geometry={nodes.Cylinder021.geometry} material={materials['metal.002']} position={[0, 0.489, -2.482]} />
          <mesh name="Cylinder022" geometry={nodes.Cylinder022.geometry} material={materials['paint.003']} position={[0, -0.003, -15.212]} rotation={[0, 0, -Math.PI]} />
          <mesh name="Cylinder023" geometry={nodes.Cylinder023.geometry} material={materials['paint.003']} position={[0, 0.827, -15.144]} rotation={[0, 0, -Math.PI]} />
          <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials['metal.002']} position={[0, 0.489, -15.143]} rotation={[0, 0, -Math.PI]} />
          <mesh name="Cylinder025" geometry={nodes.Cylinder025.geometry} material={materials['metal.002']} position={[0, 1.021, -2.526]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder026" geometry={nodes.Cylinder026.geometry} material={materials['metal.002']} position={[0, 1.018, -2.651]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder027" geometry={nodes.Cylinder027.geometry} material={materials['metal.002']} position={[0, 1.021, -15.099]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder028" geometry={nodes.Cylinder028.geometry} material={materials['metal.002']} position={[0, 1.018, -14.973]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder029" geometry={nodes.Cylinder029.geometry} material={materials['metal.002']} position={[0, 0.812, -15.282]} rotation={[0.119, 0, 0]} />
          <mesh name="Cylinder030" geometry={nodes.Cylinder030.geometry} material={materials['Material.019']} position={[0, 0.032, 17.324]} />
          <group name="Cylinder031" position={[0, 5.839, 16.201]} rotation={[-1.304, 0, 0]}>
            <mesh name="Cylinder150" geometry={nodes.Cylinder150.geometry} material={materials['Material.017']} />
            <mesh name="Cylinder150_1" geometry={nodes.Cylinder150_1.geometry} material={materials['metal.003']} />
            <mesh name="Cylinder150_2" geometry={nodes.Cylinder150_2.geometry} material={materials['Material.018']} />
          </group>
          <mesh name="Cylinder032" geometry={nodes.Cylinder032.geometry} material={materials['metal.002']} position={[0.15, 0.042, 17.171]} />
          <mesh name="Cylinder033" geometry={nodes.Cylinder033.geometry} material={materials['metal.002']} position={[-0.15, 0.042, 17.171]} />
          <mesh name="Cylinder034" geometry={nodes.Cylinder034.geometry} material={materials['metal.002']} position={[0.15, 0.042, 17.472]} />
          <mesh name="Cylinder035" geometry={nodes.Cylinder035.geometry} material={materials['metal.002']} position={[-0.15, 0.042, 17.472]} />
          <mesh name="Cylinder036" geometry={nodes.Cylinder036.geometry} material={materials['Material.019']} position={[-15.153, 0.032, 17.287]} rotation={[0, -Math.PI / 4, 0]} />
          <group name="Cylinder037" position={[-14.359, 5.839, 16.493]} rotation={[-1.38, -0.187, -0.767]}>
            <mesh name="Cylinder144" geometry={nodes.Cylinder144.geometry} material={materials['Material.017']} />
            <mesh name="Cylinder144_1" geometry={nodes.Cylinder144_1.geometry} material={materials['metal.003']} />
            <mesh name="Cylinder144_2" geometry={nodes.Cylinder144_2.geometry} material={materials['Material.018']} />
          </group>
          <mesh name="Cylinder038" geometry={nodes.Cylinder038.geometry} material={materials['metal.002']} position={[-14.939, 0.042, 17.285]} rotation={[0, -Math.PI / 4, 0]} />
          <mesh name="Cylinder039" geometry={nodes.Cylinder039.geometry} material={materials['metal.002']} position={[-15.151, 0.042, 17.073]} rotation={[0, -Math.PI / 4, 0]} />
          <mesh name="Cylinder040" geometry={nodes.Cylinder040.geometry} material={materials['metal.002']} position={[-15.152, 0.042, 17.498]} rotation={[0, -Math.PI / 4, 0]} />
          <mesh name="Cylinder041" geometry={nodes.Cylinder041.geometry} material={materials['metal.002']} position={[-15.364, 0.042, 17.286]} rotation={[0, -Math.PI / 4, 0]} />
          <group name="Cylinder043" position={[-14.03, 5.839, 0]} rotation={[-Math.PI / 2, -0.267, -Math.PI / 2]}>
            <mesh name="Cylinder138" geometry={nodes.Cylinder138.geometry} material={materials['Material.017']} />
            <mesh name="Cylinder138_1" geometry={nodes.Cylinder138_1.geometry} material={materials['metal.003']} />
            <mesh name="Cylinder138_2" geometry={nodes.Cylinder138_2.geometry} material={materials['Material.018']} />
          </group>
          <mesh name="Cylinder044" geometry={nodes.Cylinder044.geometry} material={materials['metal.002']} position={[-15, 0.042, 0.15]} rotation={[0, -1.571, 0]} />
          <mesh name="Cylinder045" geometry={nodes.Cylinder045.geometry} material={materials['metal.002']} position={[-15, 0.042, -0.15]} rotation={[0, -1.571, 0]} />
          <mesh name="Cylinder046" geometry={nodes.Cylinder046.geometry} material={materials['metal.002']} position={[-15.301, 0.042, 0.15]} rotation={[0, -1.571, 0]} />
          <mesh name="Cylinder047" geometry={nodes.Cylinder047.geometry} material={materials['metal.002']} position={[-15.301, 0.042, -0.15]} rotation={[0, -1.571, 0]} />
          <mesh name="Cylinder050" geometry={nodes.Cylinder050.geometry} material={materials['metal.002']} position={[15.151, 0.042, 17.073]} rotation={[0, Math.PI / 4, 0]} />
          <mesh name="Cylinder051" geometry={nodes.Cylinder051.geometry} material={materials['metal.002']} position={[14.939, 0.042, 17.285]} rotation={[0, Math.PI / 4, 0]} />
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['metal.002']} position={[15.364, 0.042, 17.286]} rotation={[0, Math.PI / 4, 0]} />
          <mesh name="Cylinder053" geometry={nodes.Cylinder053.geometry} material={materials['metal.002']} position={[15.152, 0.042, 17.498]} rotation={[0, Math.PI / 4, 0]} />
          <mesh name="Cylinder054" geometry={nodes.Cylinder054.geometry} material={materials['Material.019']} position={[15.153, 0.032, 0]} rotation={[0, 1.571, 0]} />
          <group name="Cylinder055" position={[14.03, 5.839, 0]} rotation={[-Math.PI / 2, 0.267, Math.PI / 2]}>
            <mesh name="Cylinder126" geometry={nodes.Cylinder126.geometry} material={materials['Material.017']} />
            <mesh name="Cylinder126_1" geometry={nodes.Cylinder126_1.geometry} material={materials['metal.003']} />
            <mesh name="Cylinder126_2" geometry={nodes.Cylinder126_2.geometry} material={materials['Material.018']} />
          </group>
          <mesh name="Cylinder056" geometry={nodes.Cylinder056.geometry} material={materials['metal.002']} position={[15, 0.042, -0.15]} rotation={[0, 1.571, 0]} />
          <mesh name="Cylinder057" geometry={nodes.Cylinder057.geometry} material={materials['metal.002']} position={[15, 0.042, 0.15]} rotation={[0, 1.571, 0]} />
          <mesh name="Cylinder058" geometry={nodes.Cylinder058.geometry} material={materials['metal.002']} position={[15.301, 0.042, -0.15]} rotation={[0, 1.571, 0]} />
          <mesh name="Cylinder059" geometry={nodes.Cylinder059.geometry} material={materials['metal.002']} position={[15.301, 0.042, 0.15]} rotation={[0, 1.571, 0]} />
          <mesh name="Cylinder060" geometry={nodes.Cylinder060.geometry} material={materials['Material.019']} position={[0, 0.032, -17.324]} rotation={[Math.PI, 0, Math.PI]} />
          <group name="Cylinder061" position={[0, 5.839, -16.201]} rotation={[-1.838, 0, -Math.PI]}>
            <mesh name="Cylinder120" geometry={nodes.Cylinder120.geometry} material={materials['Material.017']} />
            <mesh name="Cylinder120_1" geometry={nodes.Cylinder120_1.geometry} material={materials['metal.003']} />
            <mesh name="Cylinder120_2" geometry={nodes.Cylinder120_2.geometry} material={materials['Material.018']} />
          </group>
          <mesh name="Cylinder062" geometry={nodes.Cylinder062.geometry} material={materials['metal.002']} position={[-0.15, 0.042, -17.171]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh name="Cylinder063" geometry={nodes.Cylinder063.geometry} material={materials['metal.002']} position={[0.15, 0.042, -17.171]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh name="Cylinder064" geometry={nodes.Cylinder064.geometry} material={materials['metal.002']} position={[-0.15, 0.042, -17.472]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh name="Cylinder065" geometry={nodes.Cylinder065.geometry} material={materials['metal.002']} position={[0.15, 0.042, -17.472]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh name="Cylinder066" geometry={nodes.Cylinder066.geometry} material={materials['Material.019']} position={[15.153, 0.032, -17.287]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
          <group name="Cylinder067" position={[14.359, 5.839, -16.493]} rotation={[-1.762, 0.187, 2.374]}>
            <mesh name="Cylinder114" geometry={nodes.Cylinder114.geometry} material={materials['Material.017']} />
            <mesh name="Cylinder114_1" geometry={nodes.Cylinder114_1.geometry} material={materials['metal.003']} />
            <mesh name="Cylinder114_2" geometry={nodes.Cylinder114_2.geometry} material={materials['Material.018']} />
          </group>
          <mesh name="Cylinder068" geometry={nodes.Cylinder068.geometry} material={materials['metal.002']} position={[14.939, 0.042, -17.285]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
          <mesh name="Cylinder069" geometry={nodes.Cylinder069.geometry} material={materials['metal.002']} position={[15.151, 0.042, -17.073]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
          <mesh name="Cylinder070" geometry={nodes.Cylinder070.geometry} material={materials['metal.002']} position={[15.152, 0.042, -17.498]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
          <mesh name="Cylinder071" geometry={nodes.Cylinder071.geometry} material={materials['metal.002']} position={[15.364, 0.042, -17.286]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
          <mesh name="Cylinder074" geometry={nodes.Cylinder074.geometry} material={materials['metal.002']} position={[-15.151, 0.042, -17.073]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
          <mesh name="Cylinder075" geometry={nodes.Cylinder075.geometry} material={materials['metal.002']} position={[-14.939, 0.042, -17.285]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
          <mesh name="Cylinder076" geometry={nodes.Cylinder076.geometry} material={materials['metal.002']} position={[-15.364, 0.042, -17.286]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
          <mesh name="Cylinder077" geometry={nodes.Cylinder077.geometry} material={materials['metal.002']} position={[-15.152, 0.042, -17.498]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
          <mesh name="Cylinder080" geometry={nodes.Cylinder080.geometry} material={materials['metal.002']} position={[0.15, 0.042, -0.153]} />
          <mesh name="Cylinder081" geometry={nodes.Cylinder081.geometry} material={materials['metal.002']} position={[-0.15, 0.042, -0.153]} />
          <mesh name="Cylinder082" geometry={nodes.Cylinder082.geometry} material={materials['metal.002']} position={[0.15, 0.042, 0.148]} />
          <mesh name="Cylinder083" geometry={nodes.Cylinder083.geometry} material={materials['metal.002']} position={[-0.15, 0.042, 0.148]} />
          <mesh name="Cylinder085" geometry={nodes.Cylinder085.geometry} material={materials['metal.002']} position={[3.692, 1.335, -17.537]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder086" geometry={nodes.Cylinder086.geometry} material={materials['paint.004']} position={[0, -0.002, 16.208]} />
          <mesh name="Cylinder087" geometry={nodes.Cylinder087.geometry} material={materials['metal.002']} position={[-8.064, 1.335, -17.537]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cylinder088" geometry={nodes.Cylinder088.geometry} material={materials['paint.004']} position={[0, -0.002, 16.208]} />
          <group name="Cylinder089" position={[0, -0.004, 16.202]}>
            <mesh name="Cylinder092" geometry={nodes.Cylinder092.geometry} material={materials['paint.004']} />
            <mesh name="Cylinder092_1" geometry={nodes.Cylinder092_1.geometry} material={materials['Material.017']} />
          </group>
          <mesh name="Cylinder090" geometry={nodes.Cylinder090.geometry} material={materials['metal.002']} position={[3.725, 1.335, 17.537]} rotation={[Math.PI, 0, Math.PI / 2]} />
          <mesh name="NurbsPath" geometry={nodes.NurbsPath.geometry} material={materials['Material.016']} position={[0, 0, 8.813]} />
          <mesh name="NurbsPath002" geometry={nodes.NurbsPath002.geometry} material={materials['Material.014']} position={[0, 0.772, 2.341]} rotation={[0.054, 0, 0]} />
          <mesh name="NurbsPath003" geometry={nodes.NurbsPath003.geometry} material={materials['Material.014']} position={[0, 0.928, 8.813]} />
          <mesh name="NurbsPath004" geometry={nodes.NurbsPath004.geometry} material={materials['Material.016']} position={[0, 0, -8.813]} />
          <mesh name="NurbsPath005" geometry={nodes.NurbsPath005.geometry} material={materials['Material.015']} position={[0, 0.175, -8.812]} />
          <mesh name="NurbsPath006" geometry={nodes.NurbsPath006.geometry} material={materials['Material.014']} position={[0, 0.928, -8.813]} />
          <mesh name="NurbsPath007" geometry={nodes.NurbsPath007.geometry} material={materials['Material.014']} position={[0, 0.772, -15.284]} rotation={[0.054, 0, 0]} />
          <mesh name="Phillips_Screw_Head001" geometry={nodes.Phillips_Screw_Head001.geometry} material={materials['brass.001']} position={[0.03, 0.687, 15.252]} rotation={[Math.PI / 2, 0, -0.692]} />
          <mesh name="Phillips_Screw_Head003" geometry={nodes.Phillips_Screw_Head003.geometry} material={materials['brass.001']} position={[-0.031, 0.819, 15.252]} rotation={[-Math.PI / 2, 0, -0.692]} />
          <mesh name="Phillips_Screw_Head004" geometry={nodes.Phillips_Screw_Head004.geometry} material={materials['brass.001']} position={[-0.031, 0.687, 15.252]} rotation={[-Math.PI / 2, 0, -0.692]} />
          <mesh name="Phillips_Screw_Head005" geometry={nodes.Phillips_Screw_Head005.geometry} material={materials['brass.001']} position={[0.03, 0.687, -2.373]} rotation={[Math.PI / 2, 0, -0.692]} />
          <mesh name="Phillips_Screw_Head006" geometry={nodes.Phillips_Screw_Head006.geometry} material={materials['brass.001']} position={[-0.031, 0.819, -2.373]} rotation={[-Math.PI / 2, 0, -0.692]} />
          <mesh name="Phillips_Screw_Head007" geometry={nodes.Phillips_Screw_Head007.geometry} material={materials['brass.001']} position={[-0.031, 0.687, -2.373]} rotation={[-Math.PI / 2, 0, -0.692]} />
          <mesh name="Phillips_Screw_Head008" geometry={nodes.Phillips_Screw_Head008.geometry} material={materials['brass.001']} position={[0.03, 0.819, -2.373]} rotation={[Math.PI / 2, 0, -0.692]} />
          <mesh name="Phillips_Screw_Head009" geometry={nodes.Phillips_Screw_Head009.geometry} material={materials['brass.001']} position={[0.03, 0.819, 15.252]} rotation={[Math.PI / 2, 0, -0.692]} />
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.013']} position={[0, 0, 8.813]} />
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['tarp.001']} position={[0, 1.022, 8.813]} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.011']} position={[0, 0.041, 8.813]} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.013']} position={[0, 0.013, 8.819]} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.Grass} position={[0, 0, -8.813]} />
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['tarp.001']} position={[0, 1.022, -8.813]} />
          <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.011']} position={[0, 0.041, -8.813]} />
          <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.010']} position={[1.31, 1.469, -17.524]} />
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.010']} position={[6.106, 1.469, 17.523]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['paint.003']} position={[0, 1.012, 15.212]} />
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['paint.003']} position={[0, 1.012, 2.412]} rotation={[0, 0, -Math.PI]} />
          <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['paint.003']} position={[0, 1.012, -2.413]} />
          <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials['paint.003']} position={[0, 1.012, -15.212]} rotation={[0, 0, -Math.PI]} />
          <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials['paint.003']} position={[0, 0.766, 2.343]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials['metal.002']} position={[0, 0.042, 8.813]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={materials['paint.003']} position={[0, 0.766, -15.282]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Torus003" geometry={nodes.Torus003.geometry} material={materials['metal.002']} position={[0, 0.042, -8.813]} rotation={[0, 0, -Math.PI / 2]} />
        </group>
        <pointLight name="Light" intensity={54351.413} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
        <directionalLight intensity={2049} decay={2} color="#f6ffc1" rotation={[-Math.PI / 2, 0, 0]} target={nodes.Sun.target}>
          <primitive object={nodes.Sun.target} position={[0, 0, -1]} />
        </directionalLight>
        <mesh name="Center_Lamppost" geometry={nodes.Center_Lamppost.geometry} material={materials.Material}>
          <group name="Cylinder079" position={[0, 5.839, -1.123]} rotation={[-1.304, 0, 0]}>
            <mesh name="Cylinder102" geometry={nodes.Cylinder102.geometry} material={materials['Material.017']} />
            <mesh name="Cylinder102_1" geometry={nodes.Cylinder102_1.geometry} material={materials['metal.003']} />
            <mesh name="Cylinder102_2" geometry={nodes.Cylinder102_2.geometry} material={materials['Material.018']} />
            <mesh name="Cylinder078" geometry={nodes.Cylinder078.geometry} material={materials['Material.019']} position={[0, -2.614, -5.306]} rotation={[1.304, 0, 0]} />
            <group name="Cylinder084" position={[0, -2.167, 0.592]} rotation={[2.608, 0, -Math.PI]}>
              <mesh name="Cylinder097" geometry={nodes.Cylinder097.geometry} material={materials['Material.017']} />
              <mesh name="Cylinder097_1" geometry={nodes.Cylinder097_1.geometry} material={materials['metal.003']} />
              <mesh name="Cylinder097_2" geometry={nodes.Cylinder097_2.geometry} material={materials['Material.018']} />
            </group>
          </group>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/tennis-court.gltf')
